language: node_js
node_js:
  - "14.16.0"
branches:
  only:
    - master
    - develop
notifications:  
  email:
    recipients:
      - open.hardware.libre@gmail.com
deploy:
  provider: heroku
  api_key: $HEROKU  
  app: 
    develop: sip-property-management-angula