language: node_js
node_js:
  - "14.16.0"
addons:
  sonarcloud:
    organization: "sip-informatica"
    token: $SONAR
branches:
  only:
    - master
    - develop
notifications:  
  email:
    recipients:
      - open.hardware.libre@gmail.com
before_script:
  - npm install -g @angular/cli
install:
  - npm install
script:
  - ng lint
  - ng build --prod
  - sonar-scanner
deploy:
  provider: heroku
  api_key: $HEROKU  
  app: 
    develop: sip-property-management-angula