language: node_js
node_js:
  - "14.16.0"
branches:
  only:
    - master
    - develop
notifications:  
  email:
    recipients:
      - open.hardware.libre@gmail.com
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - ng build --prod
deploy:
  provider: heroku
  api_key: $HEROKU  
  app: 
    develop: sip-property-management-angula